# Generated by Django 3.2.18 on 2023-04-26 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_auto_20230426_1708'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.TextField(default=0, max_length=250),
            preserve_default=False,
        ),
    ]
